### ISSUE TITLE
Worth mentioning Birthday Problem in README?

### ISSUE THREAD

**Issue by mtharrison** [rjrodger/nid#6]
Do you think it's worth mentioning Birthday Problem in the README? The default settings (alphabet of 36 and length of 6) give an identifier space of 2,176,782,336 unique IDs. There's a 50% probability of collisions after only generating about 55,000 identifiers and 99% probability of collision after 141,594 IDs generated? (actually less probably because of skipping curse words)

This could be important to know for people generating unique identifiers to associate with requests, for instance.

**Comment by rjrodger** [comment]
yes :)
